### ISSUE TITLE
Chai and Mocha missing in package.json?

### ISSUE THREAD

**Issue by supersven** [jneen/parsimmon#58]
Hello,

Thank you for this parser library. I have a lot of fun playing around with it! :)

After cloning the project I noticed that it doesn't build on my machine, because the node modules 'mocha' and 'chai' were missing:

```bash
sven@muckelmaus ~/s/parsimmon> make test
./node_modules/.bin/mocha -u tdd ./test/intro.js ./test/*.test.js
/bin/sh: 1: ./node_modules/.bin/mocha: not found
Makefile:38: recipe for target 'test' failed
make: *** [test] Error 127
sven@muckelmaus ~/s/parsimmon> npm install mocha --save-dev
npm WARN package.json parsimmon@0.6.0 No license field.
mocha@2.3.4 node_modules/mocha
├── diff@1.4.0
├── escape-string-regexp@1.0.2
├── commander@2.3.0
├── supports-color@1.2.0
├── growl@1.8.1
├── debug@2.2.0 (ms@0.7.1)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)
└── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
sven@muckelmaus ~/s/parsimmon> make test
./node_modules/.bin/mocha -u tdd ./test/intro.js ./test/*.test.js
module.js:340
    throw err;
    ^

Error: Cannot find module 'chai'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/sven/src/parsimmon/test/intro.js:1:79)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /home/sven/src/parsimmon/node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/sven/src/parsimmon/node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (/home/sven/src/parsimmon/node_modules/mocha/lib/mocha.js:453:10)
    at Object.<anonymous> (/home/sven/src/parsimmon/node_modules/mocha/bin/_mocha:393:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
Makefile:38: recipe for target 'test' failed
make: *** [test] Error 1
sven@muckelmaus ~/s/parsimmon> npm install chai --save-dev
npm WARN package.json parsimmon@0.6.0 No license field.
chai@3.4.1 node_modules/chai
├── assertion-error@1.0.1
├── type-detect@1.0.0
└── deep-eql@0.1.3 (type-detect@0.1.1)
```
`npm install mocha --save-dev` and `npm install chai --save-dev` did the trick. There are now two additional entries in package.json:

```json
  "devDependencies": {
    "chai": "^3.4.1",
    "mocha": "^2.3.4",
...
  },
```

Should I file a pull request for this (very small) change? It might be that the version numbers don't fit to the project as there is still one failing test:

```bash
sven@muckelmaus ~/s/parsimmon> make test
./node_modules/.bin/mocha -u tdd ./test/intro.js ./test/*.test.js


  parser
    ✓ Parsimmon.string
    ✓ Parsimmon.regex
    ✓ Parsimmon.regex with group
    1) Parsimmon.seq
    ✓ Parsimmon.alt
    ✓ eof
    ✓ test
    ✓ takeWhile
    ✓ index
    ✓ mark
    Parsimmon.custom
      ✓ simple parser definition
      ✓ failing parser
      ✓ composes with existing parsers
    Parsimmon.sepBy/sepBy1
      ✓ successful, returns an array of parsed elements
      ✓ sepBy succeeds with the empty list on empty input, sepBy1 fails
      ✓ does not tolerate trailing separators
    then
      ✓ with a parser, uses the last return value
    chain
      ✓ asserts that a parser is returned
      ✓ with a function that returns a parser, continues with that parser
    map
      ✓ with a function, pipes the value in and uses that return value
    result
      ✓ returns a constant result
    skip
      ✓ uses the previous return value
    or
      ✓ two parsers
      ✓ with chain
    many
      ✓ simple case
      ✓ followed by then
    times
      ✓ zero case
      ✓ nonzero case
      ✓ with a min and max
      ✓ atMost
      ✓ atLeast
    fail
      ✓ use Parsimmon.fail to fail dynamically
      ✓ use Parsimmon.succeed or Parsimmon.fail to branch conditionally
    smart error messages
      or
        ✓ prefer longest branch
        ✓ prefer last of equal length branches
        ✓ prefer longest branch even after a success
      many
        ✓ prefer longest branch even in a .many()
        ✓ prefer longest branch in .or() nested in .many()
      times
        ✓ prefer longest branch in .times() too
      desc
        ✓ allows custom error messages
        ✓ allows tagging with `lazy`


  40 passing (93ms)
  1 failing

  1) parser Parsimmon.seq:

      AssertionError: expected [ Array(3) ] to deeply equal [ '(', 'string between parens', ')' ]
      + expected - actual

       [
         "("
      -  [
      -    "s"
      -    "t"
      -    "r"
      -    "i"
      -    "n"
      -    "g"
      -    " "
      -    "b"
      -    "e"
      -    "t"
      -    "w"
      -    "e"
      -    "e"
      -    "n"
      -    " "
      -    "p"
      -    "a"
      -    "r"
      -    "e"
      -    "n"
      -    "s"
      -  ]
      +  "string between parens"
         ")"
       ]
      
      at Function.assert.deepEqual (node_modules/chai/lib/chai/interface/assert.js:207:32)
      at Context.<anonymous> (test/parsimmon.test.js:62:14)



Makefile:38: recipe for target 'test' failed
make: *** [test] Error 1
```

Kind regards,

Sven

**Comment by pandanoir** [comment]
did you run `npm install` after cloning Parsimmon? decDependency of package.json contains mocha and chai.

**Comment by supersven** [comment]
Oops, I overlooked this...

Sorry & Thank you!

Sven

**Comment by wavebeem** [comment]
It sounds like this issue is resolved.
